config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/home'
  get 'dashboard/about'
  get 'dashboard/our_company'
  get 'dashboard/philosophy'
  get 'dashboard/HSEpolicy'
  get 'dashboard/tcp'
  get 'dashboard/perforation'
  get 'dashboard/contact'
  get 'dashboard/contact_success'
  get 'dashboard/downhole'
  get 'dashboard/coiled_tubing'
  get 'dashboard/e_coil'
  get 'dashboard/wireline_services'
  get 'dashboard/lwd_mwd'
  get 'dashboard/news'

  root 'dashboard#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  layout 'application'
  def home
  	
  end


  def news
  end
  

  def lwd_mwd
  end

  def about
  end

  def our_company

  end


  def wireline_services
    
  end

  def philosophy
  end


  def HSEpolicy
  end

  def tcp
  end


  def perforation
  end

  def contact
  end

  def contact_success
  end
  

  def downhole
  end

  def coiled_tubing

  end

  def e_coil

  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/contact_us/contacts/new_formtastic.html.erb
<div id="page-116" class="post-116 page type-page status-publish hentry grve-main-content">

				<section class="grve-section grve-feature-header" style="padding: 30px 128px; margin-bottom: 30px; margin-left: -128px; margin-right: -128px; background-color: rgb(240, 88, 72);">  <div class="grve-row">
		<div class="wpb_column grve-column-1">
			<h2 class="grve-element grve-align-center grve-title-no-line light-title-bges" style="">Contact TAHA</h2>
		</div>
	  </div></section><section class="grve-section" style="margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">  <div class="grve-row">
		<div class="wpb_column grve-column-1-3">
			<div class="wpcf7" id="wpcf7-f4-p116-o1" lang="en-US" dir="ltr">
<div class="screen-reader-response"></div>


<%= form_for @contact, :url => contacts_path do |f| %>
  
<p>Your Name (required)<br>
  	<%= f.text_field :name%>

    <span class="wpcf7-form-control-wrap your-name">
    </span> </p>
<p>Your Email (required)<br>
    <span class="wpcf7-form-control-wrap your-email">
	<%= f.text_field :email%>
    </span> </p>
<p>Subject<br>
    <span class="wpcf7-form-control-wrap your-subject">
<%= f.text_field :subject %>
    </span>
    </p>
<p>Your Message<br>
  <%= f.text_area :message  %>
</p>

  <%= f.submit "send"  %>

<% end %>

</div>
</div>
</div>
</section>
</div>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/dashboard/HSEpolicy.html.erb
<div id="page-766" class="post-766 page type-page status-publish hentry grve-main-content">

				<section class="grve-section grve-feature-header" style="padding: 30px 128px; margin-bottom: 90px; margin-left: -128px; margin-right: -128px; background-color: rgb(240, 88, 72);">  <div class="grve-row">
		<div class="wpb_column grve-column-1">
			<h2 class="grve-element grve-align-center grve-title-no-line light-title-bges" style="">Safety Management System Policy</h2>
		</div>
	  </div></section><section class="grve-section" style="margin-bottom: 30px; margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">  <div class="grve-row">
		<div class="wpb_column grve-column-1">
			<div class="grve-element grve-text">		
			<p>
				Taha, including management, is committed to achieving a goal of operating its business at a standard which will establish it as an industry leader in protecting the health and safety of employees and the public, as well as protecting the environment wherever we do business. With an ongoing proactive attitude towards Occupational Health, Safety & Environmental concerns, we can make this possible.
			</p>
<p>
The management of Taha is committed to our corporate policies because it is an integral part of the company’s work. Employees and contractors of Taha should use this manual to understand their role and to establish personal actions to meet the expectations described.
</p>
<p>
Employees, subcontractors and visitors who knowingly violate safety rules will face disciplinary action, dismissal or legal action. The Company may face legal action, fines or sanctions for violations of regulatory requirements, therefore those individuals who do not fulfill their responsibilities regarding HSE will become accountable for any problems their negligence creates and may be liable under the law. All employees should be familiar with the regulatory bodies and agencies that govern our industry. Everyone employed by this Company is responsible for maintaining the safety program.
</p>
<p>
Managers and supervisors are responsible for identifying hazards, communicating and/or investigating hazards and incidents, ensuring that training is provided, ensuring that employees are supplied with and use appropriate personal protective equipment and that equipment is properly maintained and meets safety standards.
</p>
<p>
All employees must support supervisory personnel with their input and participation in the safety program, follow the safety program and government regulations. All individuals on the work site are responsible for obeying safety rules, following safe work procedures, wearing personal protective equipment, ensuring attendance at safety meetings, participation in training programs and refusing to do work when unsafe conditions exist.
</p>
<p>
In addition to protecting lives, our program contributes to employee morale and pride. All employees will participate in identifying safety needs and developing safe work procedures. By fulfilling our safety responsibilities, everyone who works for this company will share the benefits of a safe workplace. With everyone’s support and contributions, I believe we may achieve our goals of excellence in health, safety and environmental performance.
</p>
<p>Sincerely,<br>
<strong>Seyed Mohammad Tabatabaei</strong></p>
	
		</div>
	
		</div>
	  </div></section><section class="grve-section" style="margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">  <div class="grve-row">
		<div class="wpb_column grve-column-1">
			  <hr class="grve-element grve-space-divider  " style="padding-bottom: 80px;">
		</div>
	  </div></section>


			</div>

app/views/dashboard/coiled_tubing.html.erb
<div id="page-328" class="post-328 page type-page status-publish hentry grve-main-content">
  <section class="grve-section grve-feature-header" style="margin-left: -66px; margin-right: -66px; padding-left: 66px; padding-right: 66px;">  <div class="grve-row">
    <div class="wpb_column grve-column-1">
      <div class="wpb_revslider_element wpb_content_element">

        <div style="position:relative;width:100%;height:auto;margin-top:0px;margin-bottom:0px" class="forcefullwidth_wrapper_tp_banner">
          <div id="rev_slider_11_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container"
               style=" margin: 0px auto; padding: 0px; max-height: 537px; height: 455px; left: -122px; position: absolute; width: 1424px; overflow: visible; background-color: rgb(233, 233, 233);">
          <div id="rev_slider_11_1" class="rev_slider fullwidthabanner revslider-initialised tp-simpleresponsive" style="max-height: 537px; height: 455px; background-image: none; background-color: rgb(233, 233, 233);">
            <ul style="display: block; overflow: hidden; width: 100%; height: 100%; max-height: 537px;">
              <!-- SLIDE  -->
              <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-saveperformance="off" style="width: 100%; height: 100%; overflow: hidden; visibility: visible; left: 0px; top: 0px; opacity: 1; z-index: 20;" class="current-sr-slide-visible">
                <!-- MAIN IMAGE -->
                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center top" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat" data-lazydone="undefined" src="http://www.bges.ca/wp-content/uploads/2014/10/header-open-hole-logging.jpg" data-src="http://www.bges.ca/wp-content/uploads/2014/10/header-open-hole-logging.jpg" style="  width: 100%; height: 100%; opacity: 1; position: relative; background-image: url(../images/ecoil.png); background-color: rgba(0, 0, 0, 0); background-size: cover; background-position: 50% 0%; background-repeat: no-repeat;"></div></div>
                <!-- LAYERS -->
              </li>
            </ul>
            <div class="tp-static-layers">
            </div>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important; width: 0%;"></div>
            <div class="tp-loader spinner4" style="display: none;"><div class="dot1"></div><div class="dot2"></div><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div></div>

        </div>
          <div class="tp-fullwidth-forcer" style="width: 100%; height: 455px;"></div>
        </div>

        <!-- END REVOLUTION SLIDER --></div>

    </div>
  </div></section>





  <section class="grve-section" style="padding: 30px 66px; margin-bottom: 90px; margin-left: -66px; margin-right: -66px; background-color: rgb(240, 88, 72);">  <div class="grve-row">
    <div class="wpb_column grve-column-1">
      <h2 class="grve-element grve-align-center grve-title-no-line light-title-bges" style="">Coiled Tubing</h2>
    </div>
  </div>
  </section>

  <section class="grve-section" style="margin-left: -66px; margin-right: -66px; padding-left: 66px; padding-right: 66px;">  <div class="grve-row">
    <div class="wpb_column grve-column-1">
      <div class="grve-element grve-text">
        <p>
          In today's dynamic horizontal completion market, service providers must be able to adapt and deliver

          high quality solution. TPK's coiled tubing units are a quick and cost effective piece of equipment that can

          be used for various applications  including acidizing, acid jetting, milling, setting and retrieving bridge

          plugs, perforating, cleanouts and logging. The advantage of TPK's coiled tubing units are the speed of

          getting into and out of the well and its ability to work on a producing well while it is still under pressure.

          Having the versatility of conventional  wireline and the rigidness of tubing, coil tubes have proven to be

          a reliable and safe method in reducing completion costs.
        </p>
        <p>
          TPK's E-Coil equipment incorporates the latest in advanced equipment technology and operating control

          techniques. Each coiled tubing unit provides real time data acquisition to accurately capture the job

          information needed to perform every treatment with precision. TPK's E-Coil advantages are:

          <br>
        <p style="padding-left:5em;">
          * Accurately placement of perforations, tools, etc. as they are logged into place.<br>

          * More cost effective down hole tractors.<br>

          * No increased power demands on E-Line hardware to run tractor.<br>

          * Faster rig up than conventional trailer units.<br>

          * More reliable than memory tool - There is real tread out.<br>

          * Real time readout allows changes to suit the down hole situation.<br>

          * Allows incredible view on cameras due to flow through tools.<br>

          * Allows complete selection of E-Line tolls - No restrictions due to memory or low battery power.<br>
        </p>
        </p>

      </div>

    </div>
  </div>
  </section>
  <section class="grve-section" style="margin-left: -66px; margin-right: -66px; padding-left: 66px; padding-right: 66px;">  <div class="grve-row">
    <div class="wpb_column grve-column-1">
      <hr class="grve-element grve-space-divider  " style="padding-bottom: 80px;">
    </div>
  </div>
  </section>


  <%= render 'shared/reachandlearn' %>

</div>

app/views/dashboard/contact.html.erb
<div id="page-116" class="post-116 page type-page status-publish hentry grve-main-content">

				<section class="grve-section grve-feature-header" style="padding: 30px 128px; margin-bottom: 30px; margin-left: -128px; margin-right: -128px; background-color: rgb(240, 88, 72);">  <div class="grve-row">
		<div class="wpb_column grve-column-1">
			<h2 class="grve-element grve-align-center grve-title-no-line light-title-bges" style="">Contact TAHA</h2>
		</div>
	  </div></section>
	  <section class="grve-section" style="margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">  <div class="grve-row">
		<div class="wpb_column grve-column-1-3">
			<div class="wpcf7" id="wpcf7-f4-p116-o1" lang="en-US" dir="ltr">

<form name="" action="/contact-bges/#wpcf7-f4-p116-o1" method="post" class="wpcf7-form" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="4">
<input type="hidden" name="_wpcf7_version" value="4.0.3">
<input type="hidden" name="_wpcf7_locale" value="en_US">
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f4-p116-o1">
<input type="hidden" name="_wpnonce" value="d040d1e359">
</div>

<p>Your Name (required)<br>
    <span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false"></span> </p>
<p>Your Email (required)<br>
    <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false"></span> </p>
<p>Subject<br>
    <span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false"></span> </p>
<p>Your Message<br>
    <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false"></textarea></span> </p>
<p><input type="hidden" name="_wpcf7_captcha_challenge_captcha-238" value="2087822919"><img class="wpcf7-form-control wpcf7-captchac wpcf7-captcha-captcha-238" width="84" height="28" alt="captcha" src="http://www.bges.ca/wp-content/uploads/wpcf7_captcha/2087822919.png"><br>
    <span class="wpcf7-form-control-wrap captcha-238"><input type="text" name="captcha-238" value="" size="40" class="wpcf7-form-control wpcf7-captchar" aria-invalid="false"></span></p>
<p><input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://www.bges.ca/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;"></p>
<div class="wpcf7-response-output wpcf7-display-none"></div></form>
</div>
		</div>
	</div>
	</section>
	</div>

app/views/dashboard/contact_success.html.erb
<div id="page-116" class="post-116 page type-page status-publish hentry grve-main-content">

				<section class="grve-section grve-feature-header" style="padding: 30px 128px; margin-bottom: 30px; margin-left: -128px; margin-right: -128px; background-color: rgb(240, 88, 72);">  <div class="grve-row">
		<div class="wpb_column grve-column-1">
			<h4 class="grve-element grve-align-center grve-title-no-line light-title-bges" style="">
			Email Recieved</h4>
		</div>
	  </div>
	  </section>


	  <section class="grve-section" style="margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">
	   <div class="grve-row" style="text-align:center">
	  <p>
	  You have successfully sent us your message, we will contact you back. 
	  </p>
          </div>
        </section>
	  </div>

app/views/dashboard/philosophy.html.erb
<div id="page-325" class="post-325 page type-page status-publish hentry grve-main-content">

  <section class="grve-section grve-feature-header" style="margin-left: -66px; margin-right: -66px; padding-left: 66px; padding-right: 66px;">
    <div class="grve-row">

    </div>
  </section>

  <section class="grve-section" style="padding: 30px 128px; margin-bottom: 90px; margin-left: -128px; margin-right: -128px; background-color: rgb(240, 88, 72);">  <div class="grve-row">
    <div class="wpb_column grve-column-1">
      <h2 class="grve-element grve-align-center grve-title-no-line light-title-bges" style="">Our Philosophy</h2>
    </div>
  </div></section><section class="grve-section" style="margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">  <div class="grve-row">
  <div class="wpb_column grve-column-1">
    <div class="grve-element grve-text">
      <p>
        We believe in applying science to prevent safety, environmental and financial disasters. With the number of failures in the oil wells and collapses in recent years becomes increasingly critical for public safety and environmental protection. Taha specializes in bridging the implementation gap by having an expert multi-disciplinary team working with specialized operations personnel resulting as a complete solution provider in Oil and Gas field.
      </p>
    </div>
  </div>
</div></section><section class="grve-section" style="margin-left: -128px; margin-right: -128px; padding-left: 128px; padding-right: 128px;">  <div class="grve-row">
  <div class="wpb_column grve-column-1">
    <hr class="grve-element grve-space-divider  " style="padding-bottom: 80px;">
  </div>
</div></section>

</div>

app/views/shared/_footer.html.erb
<footer id="grve-footer" class="grve-section">

  <section class="grve-footer-bar">
    <div class="grve-container">
      <div class="grve-row">

        <div class="grve-column-1-2">
          <div class="grve-copyright">
            Copyright 2015 - All Rights Reserved.

          </div>
        </div>
        <div class="grve-column-1-2">
          <div class="grve-second-menu">
            <ul id="menu-main-menu-1" class="menu">
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-165">
                <div class="grve-mainmenu-btn"></div>
                <%= link_to "Perforation" , dashboard_perforation_path %>
              </li>
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-137">
                <div class="grve-mainmenu-btn"></div>
                <%= link_to "Wireline Services" , dashboard_wireline_services_path %>
              </li>
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-505">
                <%= link_to "Coiled Tubing" , dashboard_coiled_tubing_path %>
              </li>
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-505">
                <%= link_to "E-Coiled Tubing" , dashboard_e_coil_path %>
              </li>
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-320">
                <div class="grve-mainmenu-btn"></div>
                <%= link_to "about TAHA" , dashboard_about_path %>
              </li>
              <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-130">
                <a href="#">Contact TAHA</a></li> -->
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>


</footer>

app/views/shared/_header.html.erb
    <header id="grve-header" class="grve-style-2 grve-header-dark" data-height="90" style="position: fixed; top: 0px;">
      <div class="grve-container">
        <h1 class="grve-logo" style="">
          <a href="/">
          <%= image_tag "logo1.jpg" %>
          </a>
        </h1>


        <ul class="grve-header-options">
          <li>
            <a href="#" class="grve-menu-btn">
              <!--<img src="./TAHA – Big Guns Energy Services Inc._files/menu-button.svg" alt="Main Menu">-->
            <%= image_tag "menu-button.svg" %>
            </a>
          </li>
        </ul>

        <nav class="grve-horizontal-menu">
          <ul id="menu-main-menu" class="grve-menu">
          <li id="menu-item-165" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-165">
          <div class="grve-mainmenu-btn"></div>

            <ul class="sub-menu">
              <li id="menu-item-261" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-261"><a href="#">Caprock Core Recovery</a></li>
              <li id="menu-item-262" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-262"><a href="#">Geotechnical Laboratory</a></li>
              <li id="menu-item-265" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-265"><a href="#">Mini-frac / DFIT</a></li>
              <li id="menu-item-264" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-264"><a href="#">Step-Rate Test</a></li>
              <li id="menu-item-263" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-263"><a href="#">Water Mobility Testing</a></li>
              <li id="menu-item-439" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-439"><a href="#">Thermal Reservoir Simulation</a></li>
              <li id="menu-item-444" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-444"><a href="#">Hydrogeology Study / Analysis</a></li>
            </ul>
          </li>
            <li id="menu-item-137" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-137"><div class="grve-mainmenu-btn"></div>
                <%= link_to "Downhole video imaging" , dashboard_downhole_path %>
            </li>

            <li id="menu-item-137" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-137"><div class="grve-mainmenu-btn"></div>
              <%= link_to "Coiled tubing" , dashboard_coiled_tubing_path %>

              <ul class="sub-menu">
                <li id="menu-item-394" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-394"><div class="grve-mainmenu-btn"></div>
                  <%= link_to "E-coil" , dashboard_e_coil_path %>
                </li>
              </ul>
            </li>

            <li id="menu-item-137" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-137"><div class="grve-mainmenu-btn"></div>
                <%= link_to "Perforation" , dashboard_perforation_path %>

              <ul class="sub-menu">
                <li id="menu-item-394" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-394"><div class="grve-mainmenu-btn"></div>
                <%= link_to "TCP" , dashboard_tcp_path %>
                </li>
              </ul>
            </li>

            <li id="menu-item-137" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-137">
              <div class="grve-mainmenu-btn"></div>
              <%= link_to "Wireline Services" , dashboard_wireline_services_path %>
              <ul class="sub-menu">
                <li id="menu-item-394" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-394"><div class="grve-mainmenu-btn"></div>
                <a href="#">Open Hole Logging</a>
                </li>
                <li id="menu-item-298" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-298"><a href="#">Cased-Hole Logging</a></li>
              </ul>
            </li>


            <li id="menu-item-505" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-505">
              <%= link_to "LWD & MWD",dashboard_lwd_mwd_path %>
            </li>
            <li id="menu-item-320" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-320 grve-menu-item-right">
              <div class="grve-mainmenu-btn"></div>
              <%= link_to "About TAHA" , dashboard_about_path %>
              <ul class="sub-menu">
                <li id="menu-item-331" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-331">
              <%= link_to "Our Company" , dashboard_our_company_path%>
                </li>

                <li id="menu-item-327" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-327">
              <%= link_to "Philosophy" , dashboard_philosophy_path %>                
                </li>
                <li id="menu-item-790" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-790">
                <%= link_to "NEWS" , dashboard_news_path %>   
                </li>

                <li id="menu-item-339" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-339">
                  <div class="grve-mainmenu-btn"></div>
              <%= link_to "HSE policy" , dashboard_HSEpolicy_path %>                

                  <ul class="sub-menu">
                    <li id="menu-item-771" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-771">
              <%= link_to "HSE policy" , dashboard_HSEpolicy_path %>                
                    
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
            <li id="menu-item-505" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-505">
              <%= link_to "Contact TAHA" , '/contact-us' %>                
            </li>

            <li id="menu-item-505" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-505">
              <%= link_to "Home" , root_path %>                
            </li>


           <!--  <li id="menu-item-130" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-130"><a href="#">Contact TAHA</a></li> -->
          </ul>							
          </nav>
      </div>


      <div id="grve-share-modal" class="grve-header-modal mfp-hide">	<div class="grve-social">		<ul><li><a href="#" target="_blank">
        <i class="fa fa-twitter"></i></a></li><li><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li><li><a href="#" target="_blank"><i class="fa fa-linkedin"></i></a></li>		</ul>	</div></div>





    </header>

app/views/shared/_reachandlearn.html.erb
<section class="grve-section grve-feature-footer" style="margin-left: -66px; margin-right: -66px; padding-left: 66px; padding-right: 66px; background-color: rgb(98, 99, 102);">  <div class="grve-row">
		<div class="wpb_column grve-column-1-2">
			  <hr class="grve-element grve-space-divider  " style="">
			  <div class="grve-element grve-text">		
			<div style="color: #fff; font-size: 1.5em; text-align: right; margin-top: 5px; margin-bottom: 40px;">Reach out and learn more.</div>
	
		</div>
	
		</div>
	
		<div class="wpb_column grve-column-1-2">
			  <hr class="grve-element grve-space-divider  " style="">
			  <div class="grve-element grve-align-left">
			  <%= link_to '/contact-us' , :class=>"grve-btn grve-btn-medium grve-btn-line" do  %>
			  <!-- <a class="grve-btn grve-btn-medium grve-btn-line" href="http://www.bges.ca/contact-bges/" target="_self" style=""> -->
			  <span>INQUIRE</span>
			  <% end %>
			  </div>
		</div>
	  </div>
	  </section>